name = "Vies Perdues"
author = "chada300"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0e21ce0f66edbb8e19acb60e39558abce9e4148625eb2f9f607ec89cc309684"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
