name = "Vies Perdues"
author = "chada300"
version = "1.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62412806c209af67b2b4c37debe8249c457aef621615cc3a8094b85e1a018b2f"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
