name = "Vies Perdues"
author = "chada300"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb366d5cdf0ceba304804b77bad46ce81a8539d057c8dd54b2863125b6d475c7"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
