name = "Vies Perdues"
author = "chada300"
version = "1.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f52ad9737e5fb0919aae6c01185800019bbcb75879f520c3217e3c0742d5edf"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
