name = "Vies Perdues"
author = "chada300"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "62684c45c392e785d37281a0ce6d8bbba16de744e4da59e2ebecc9c321145a92"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
