name = "Vies Perdues"
author = "chada300"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf8b5f8b5ddb3e3c23f9e63297e114e49aa76a1a36994621de52c0ceba07878a"

[versions]
fabric = "0.13.1"
minecraft = "1.18.1"
