name = " Paradise Lost - The Aether Reborn"
filename = "paradise-lost-1.6.7+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/IKpsG0nF/versions/1.6.7/paradise-lost-1.6.7%2B1.18.2.jar"
hash-format = "sha512"
hash = "b9d6a9c7d31a99a76f6f9ac942312c4870a481e0ce48f72dc1cd5c30b58df13b601865766dd26f8c78173e44587b74de534930ce4709f813569e26b8ba185c53"

[update]
[update.modrinth]
mod-id = "IKpsG0nF"
version = "BViwZYbB"
