name = "Architectury API (Fabric)"
filename = "architectury-4.1.35.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3712/834/architectury-4.1.35.jar"
hash-format = "murmur2"
hash = "3540111092"

[update]
[update.curseforge]
file-id = 3712834
project-id = 419697
