name = "Croptopia [FABRIC/FORGE]"
filename = "Croptopia-1.18.2-FABRIC-1.8.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3707/656/Croptopia-1.18.2-FABRIC-1.8.3.jar"
hash-format = "murmur2"
hash = "1716810998"

[update]
[update.curseforge]
file-id = 3707656
project-id = 415438
