name = "Essential Commands"
filename = "essential_commands-0.21.1-mc1.18.2.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/6VdDUivB/versions/0.21.1-mc1.18.2/essential_commands-0.21.1-mc1.18.2.jar"
hash-format = "sha512"
hash = "b5c2bdd56d9cddb6712b2acad923017b9849483c883b8f4b0783b46072bffda021a8a071cb6e157ea8f140d039decc20f3ac10ec1df18edc34e6f4ce1d9353ec"

[update]
[update.modrinth]
mod-id = "6VdDUivB"
version = "aluRnbbG"
