name = "Extra Alchemy"
filename = "extraalchemy-fabric-1.18.1-1.7.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/n0S5OkPo/versions/1.7.0/extraalchemy-fabric-1.18.1-1.7.0.jar"
hash-format = "sha512"
hash = "e26c993c4b8690ec61cf0fe7ea7b3cc9d954af83ba1623d1052a560cf3042d9c2525218fadd510cb820a4919cec293668dc2c1089005aeb9266eac088d38e581"

[update]
[update.modrinth]
mod-id = "n0S5OkPo"
version = "enpp5Ldu"
